### ISSUE TITLE
give command does not work (latest version)

### ISSUE THREAD

**Issue by Joshwoo69** [DeathCradle/Terraria-s-Dedicated-Server-Mod#110] opened 2015-07-02 08:53 UTC
when typing "give joshwoo69 1 50"
"no such item know by :50"
even though the item number / name exists.

**Comment by DeathCradle** [comment] 2015-07-02 10:22
The command is currently item name. 
I need to rectify the give command since it doesn't allow multiple matches. Anyway since the rebind version it hasn't used the ID and i forgot to remove it from the help text, sorry. I'll keep this issue open to remind me to fix it.

See here for the current item definitions that TDSM knows exactly, might save you some typo's: https://github.com/DeathCradle/Terraria-s-Dedicated-Server-Mod/blob/master/tdsm-core/Definitions/item.xml

Syncax specifically: give <playername> <quantity> "<item name>"

**Comment by D1G1T4L3CH0** [comment] 2015-07-02 23:58
I saw your post and thought it would be easier to see the items in a nicely formatted table rather than xml with all the other stuff that you don't need. So I made a page on the wiki...
https://github.com/DeathCradle/Terraria-s-Dedicated-Server-Mod/wiki/Items

**Comment by DeathCradle** [comment] 2015-07-03 03:07
@D1G1T4L3CH0  We could also do the same for NPC's

**Comment by D1G1T4L3CH0** [comment] 2015-07-03 18:50
Sure. I can do that.

**Comment by Joshwoo69** [comment] 2015-07-07 10:32
so close it or what?

**Comment by DeathCradle** [comment] 2015-07-07 10:45
No, the problem isn't fixed yet.

**Comment by D1G1T4L3CH0** [comment] 2015-07-07 21:13
Can't we add using ID as an option? it's makes typing it multiple times easier.

**Comment by Joshwoo69** [comment] 2015-07-08 12:10
true.

**Comment by DeathCradle** [comment] 2015-07-08 14:06
That was the plan ;)

**Comment by Stickiler** [comment] 2015-07-23 12:08
The give command has been updated to properly support using the Item ID in place of the name, as well as providing the option for a prefix.The help text has been updated to show new functionality.

Fixed in commit 85423eb3c65367cb1a23d4da25dd513b98d40753

**Closed by Stickiler** 2015-07-23 12:08 UTC
Labels: P4: Low
