### ISSUE TITLE
Official config options ignored with -config option if -world is not used

### ISSUE THREAD

**Issue by ZeroKnight** [DeathCradle/Terraria-s-Dedicated-Server-Mod#129] opened 2015-07-10 06:00 UTC
I'm attempting to run TDSM with a config file. I've used the default **serverconfig.txt** as a template and set all the relevant options (`world`, `port`, `maxplayers`, etc). However, when starting the server it still prompts me for a World (interestingly, `worldpath` seemed to have taken, as my world is listed), max number of players, port, password, UPnP, etc. as if I never set anything. The TDSM related options **are** being set (rcon, webserver) however.

Interestingly, if I specify the `-world <myworldhere>` option in the command then everything works fine; port, maxplayers, password, etc. are all set properly. So it seems to me that the `world` option is not being read from the config properly?

This applies to commit ab8d648f0530f0f7e8a3653cd85c2a13d41479cd. Here is my [serverconfig.txt](http://sprunge.us/OULg), and the command line I'm using:

    mono --server tdsm.exe -config Data/serverconfig.txt    # world option not applied

Whereas this works just fine:

    mono --server tdsm.exe -config Data/serverconfig.txt -world ../../Worlds/dz_large_expert.wld

**Comment by D1G1T4L3CH0** [comment] 2015-07-10 06:58
Confirmed on Windows and Linux.

**Comment by D1G1T4L3CH0** [comment] 2015-07-10 07:10
Btw, what does that `--server` option do? I haven't seen that one, even in `mono --help`.

**Comment by ZeroKnight** [comment] 2015-07-10 07:30
> Btw, what does that `--server` option do? I haven't seen that one, even in `mono --help`.

From mono(1) man page:
> Configures the virtual machine to be better suited for server operations (currently, allows a heavier threadpool initialization).

From some [release info](http://www.mono-project.com/docs/about-mono/releases/3.2.3/) on mono-project.com:
> Run mono with –server to tell the runtime to target performance. With this release, this means an aggressive threadpool scheduler that creates additional threads faster.

Can't find much more information beyond that, though.

**Comment by D1G1T4L3CH0** [comment] 2015-07-14 07:59
This seems to be resolved for me. @ZeroKnight can you confirm?

**Comment by ZeroKnight** [comment] 2015-07-14 11:13
> This seems to be resolved for me. @ZeroKnight can you confirm?

Still happens to me with 9cb2abbda8a72c70caed7be51985f0834788c3bd

**Comment by Stickiler** [comment] 2015-07-20 01:59
We're still unable to replicate this issue, @ZeroKnight Can you check to make sure you don't have permissions errors, and the config file doesn't contain any strange characters?

**Comment by ZeroKnight** [comment] 2015-07-21 19:49
No idea which commit fixed it, but it's working fine now. Thanks guys!

**Comment by D1G1T4L3CH0** [comment] 2015-07-21 20:03
Awesome! Glad it's working for you now. Closing as resolved.

**Closed** 2015-07-21 21:48 UTC
Labels: P4: Low
